<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Karyawan;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $karyawan = new Karyawan(['user_id'=>'1','unit_kerja_id'=>'1','jabatan_id'=>'1','status_karyawan_id'=>'3','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'2','unit_kerja_id'=>'2','jabatan_id'=>'3','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'3','unit_kerja_id'=>'2','jabatan_id'=>'3','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'4','unit_kerja_id'=>'2','jabatan_id'=>'3','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'5','unit_kerja_id'=>'2','jabatan_id'=>'3','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'6','unit_kerja_id'=>'2','jabatan_id'=>'3','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'7','unit_kerja_id'=>'2','jabatan_id'=>'3','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'8','unit_kerja_id'=>'4','jabatan_id'=>'11','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'9','unit_kerja_id'=>'4','jabatan_id'=>'12','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'10','unit_kerja_id'=>'4','jabatan_id'=>'13','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'11','unit_kerja_id'=>'4','jabatan_id'=>'14','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'12','unit_kerja_id'=>'4','jabatan_id'=>'13','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'13','unit_kerja_id'=>'4','jabatan_id'=>'13','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'14','unit_kerja_id'=>'4','jabatan_id'=>'13','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'15','unit_kerja_id'=>'4','jabatan_id'=>'13','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'16','unit_kerja_id'=>'4','jabatan_id'=>'13','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'17','unit_kerja_id'=>'6','jabatan_id'=>'15','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'18','unit_kerja_id'=>'6','jabatan_id'=>'16','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'19','unit_kerja_id'=>'6','jabatan_id'=>'17','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'20','unit_kerja_id'=>'6','jabatan_id'=>'18','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'21','unit_kerja_id'=>'6','jabatan_id'=>'16','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'22','unit_kerja_id'=>'6','jabatan_id'=>'18','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'23','unit_kerja_id'=>'6','jabatan_id'=>'19','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'24','unit_kerja_id'=>'6','jabatan_id'=>'20','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'25','unit_kerja_id'=>'2','jabatan_id'=>'5','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'26','unit_kerja_id'=>'2','jabatan_id'=>'7','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'27','unit_kerja_id'=>'2','jabatan_id'=>'8','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'28','unit_kerja_id'=>'2','jabatan_id'=>'2','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'29','unit_kerja_id'=>'2','jabatan_id'=>'2','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'30','unit_kerja_id'=>'2','jabatan_id'=>'2','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'31','unit_kerja_id'=>'21','jabatan_id'=>'95','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'32','unit_kerja_id'=>'21','jabatan_id'=>'96','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'33','unit_kerja_id'=>'21','jabatan_id'=>'97','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'34','unit_kerja_id'=>'21','jabatan_id'=>'98','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'35','unit_kerja_id'=>'7','jabatan_id'=>'21','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'36','unit_kerja_id'=>'7','jabatan_id'=>'22','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'37','unit_kerja_id'=>'7','jabatan_id'=>'23','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'38','unit_kerja_id'=>'8','jabatan_id'=>'24','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'39','unit_kerja_id'=>'8','jabatan_id'=>'25','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'40','unit_kerja_id'=>'8','jabatan_id'=>'26','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'41','unit_kerja_id'=>'8','jabatan_id'=>'27','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'42','unit_kerja_id'=>'8','jabatan_id'=>'28','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'43','unit_kerja_id'=>'8','jabatan_id'=>'29','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'44','unit_kerja_id'=>'8','jabatan_id'=>'30','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'45','unit_kerja_id'=>'8','jabatan_id'=>'30','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'46','unit_kerja_id'=>'8','jabatan_id'=>'30','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'47','unit_kerja_id'=>'8','jabatan_id'=>'31','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'48','unit_kerja_id'=>'8','jabatan_id'=>'30','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'49','unit_kerja_id'=>'8','jabatan_id'=>'30','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'50','unit_kerja_id'=>'8','jabatan_id'=>'32','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'51','unit_kerja_id'=>'9','jabatan_id'=>'33','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'52','unit_kerja_id'=>'9','jabatan_id'=>'34','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'53','unit_kerja_id'=>'9','jabatan_id'=>'37','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'54','unit_kerja_id'=>'9','jabatan_id'=>'36','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'55','unit_kerja_id'=>'9','jabatan_id'=>'37','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'56','unit_kerja_id'=>'9','jabatan_id'=>'38','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'57','unit_kerja_id'=>'9','jabatan_id'=>'39','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'58','unit_kerja_id'=>'9','jabatan_id'=>'40','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'59','unit_kerja_id'=>'9','jabatan_id'=>'94','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'60','unit_kerja_id'=>'9','jabatan_id'=>'38','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'61','unit_kerja_id'=>'9','jabatan_id'=>'35','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'62','unit_kerja_id'=>'9','jabatan_id'=>'41','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'63','unit_kerja_id'=>'9','jabatan_id'=>'10','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'64','unit_kerja_id'=>'10','jabatan_id'=>'42','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'65','unit_kerja_id'=>'10','jabatan_id'=>'43','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'66','unit_kerja_id'=>'10','jabatan_id'=>'37','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'67','unit_kerja_id'=>'10','jabatan_id'=>'43','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'68','unit_kerja_id'=>'10','jabatan_id'=>'43','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'69','unit_kerja_id'=>'10','jabatan_id'=>'44','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'70','unit_kerja_id'=>'10','jabatan_id'=>'45','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'71','unit_kerja_id'=>'10','jabatan_id'=>'46','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'72','unit_kerja_id'=>'10','jabatan_id'=>'47','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'73','unit_kerja_id'=>'10','jabatan_id'=>'48','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'74','unit_kerja_id'=>'10','jabatan_id'=>'49','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'75','unit_kerja_id'=>'10','jabatan_id'=>'95','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'76','unit_kerja_id'=>'10','jabatan_id'=>'43','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'77','unit_kerja_id'=>'10','jabatan_id'=>'50','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'78','unit_kerja_id'=>'10','jabatan_id'=>'51','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'79','unit_kerja_id'=>'10','jabatan_id'=>'52','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'80','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'81','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'82','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'83','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'84','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'85','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'86','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'87','unit_kerja_id'=>'11','jabatan_id'=>'54','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'88','unit_kerja_id'=>'11','jabatan_id'=>'54','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'89','unit_kerja_id'=>'11','jabatan_id'=>'53','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'90','unit_kerja_id'=>'12','jabatan_id'=>'55','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'91','unit_kerja_id'=>'12','jabatan_id'=>'56','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'92','unit_kerja_id'=>'12','jabatan_id'=>'57','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'93','unit_kerja_id'=>'13','jabatan_id'=>'58','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'94','unit_kerja_id'=>'13','jabatan_id'=>'59','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'95','unit_kerja_id'=>'13','jabatan_id'=>'59','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'96','unit_kerja_id'=>'14','jabatan_id'=>'61','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'97','unit_kerja_id'=>'14','jabatan_id'=>'61','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'98','unit_kerja_id'=>'15','jabatan_id'=>'62','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'99','unit_kerja_id'=>'15','jabatan_id'=>'63','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'100','unit_kerja_id'=>'15','jabatan_id'=>'63','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'101','unit_kerja_id'=>'15','jabatan_id'=>'63','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'102','unit_kerja_id'=>'16','jabatan_id'=>'64','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'103','unit_kerja_id'=>'16','jabatan_id'=>'65','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'104','unit_kerja_id'=>'16','jabatan_id'=>'66','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'105','unit_kerja_id'=>'5','jabatan_id'=>'67','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'106','unit_kerja_id'=>'5','jabatan_id'=>'6','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'107','unit_kerja_id'=>'5','jabatan_id'=>'68','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'108','unit_kerja_id'=>'5','jabatan_id'=>'69','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'109','unit_kerja_id'=>'5','jabatan_id'=>'70','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'110','unit_kerja_id'=>'5','jabatan_id'=>'70','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'111','unit_kerja_id'=>'5','jabatan_id'=>'67','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'112','unit_kerja_id'=>'3','jabatan_id'=>'73','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'113','unit_kerja_id'=>'3','jabatan_id'=>'4','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'114','unit_kerja_id'=>'3','jabatan_id'=>'74','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'115','unit_kerja_id'=>'3','jabatan_id'=>'4','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'116','unit_kerja_id'=>'3','jabatan_id'=>'9','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'117','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'118','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'119','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'120','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'121','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'122','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'123','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'124','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'125','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'126','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'127','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'128','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'129','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'130','unit_kerja_id'=>'17','jabatan_id'=>'75','status_karyawan_id'=>'1','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'131','unit_kerja_id'=>'18','jabatan_id'=>'76','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'132','unit_kerja_id'=>'19','jabatan_id'=>'77','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'133','unit_kerja_id'=>'19','jabatan_id'=>'79','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'134','unit_kerja_id'=>'19','jabatan_id'=>'80','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'135','unit_kerja_id'=>'19','jabatan_id'=>'81','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'136','unit_kerja_id'=>'19','jabatan_id'=>'82','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'137','unit_kerja_id'=>'19','jabatan_id'=>'83','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'138','unit_kerja_id'=>'19','jabatan_id'=>'84','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'139','unit_kerja_id'=>'19','jabatan_id'=>'85','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'140','unit_kerja_id'=>'19','jabatan_id'=>'86','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'141','unit_kerja_id'=>'19','jabatan_id'=>'82','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'142','unit_kerja_id'=>'19','jabatan_id'=>'82','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'143','unit_kerja_id'=>'19','jabatan_id'=>'82','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'144','unit_kerja_id'=>'19','jabatan_id'=>'87','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'145','unit_kerja_id'=>'19','jabatan_id'=>'88','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'146','unit_kerja_id'=>'19','jabatan_id'=>'89','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'147','unit_kerja_id'=>'19','jabatan_id'=>'89','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'148','unit_kerja_id'=>'19','jabatan_id'=>'89','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'149','unit_kerja_id'=>'19','jabatan_id'=>'89','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'150','unit_kerja_id'=>'19','jabatan_id'=>'82','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'151','unit_kerja_id'=>'19','jabatan_id'=>'82','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'152','unit_kerja_id'=>'20','jabatan_id'=>'92','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'153','unit_kerja_id'=>'20','jabatan_id'=>'91','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
        $karyawan = new Karyawan(['user_id'=>'154','unit_kerja_id'=>'20','jabatan_id'=>'90','status_karyawan_id'=>'2','created_at'=>now()]);$karyawan->save();
    }
}
